//! UI 文案表（轻量：函数式翻译，key → 中/英文）。
//! 与 `i18n.rs` 的分工：这里是设置界面专属文案。

use crate::config::AdsMode;
use crate::i18n::Lang;

pub fn t(lang: Lang, key: &str) -> &'static str {
    match lang {
        Lang::Zh => zh(key),
        Lang::En => en(key),
    }
}

fn zh(key: &str) -> &'static str {
    match key {
        "title" => "ACAJA 准星设置",
        "subtitle" => "设置窗口关闭后程序退出（托盘常驻即将上线）",
        "language" => "语言",
        "theme" => "主题",
        "theme_auto" => "自动",
        "theme_light" => "浅色",
        "theme_dark" => "深色",
        "preview" => "实时预览",
        "show" => "显示准星",
        "hide" => "隐藏准星",
        "quit" => "退出程序",
        "shape_style" => "形状与样式",
        "shape" => "形状",
        "size" => "大小",
        "thickness" => "粗细",
        "opacity" => "透明度",
        "rotation" => "旋转",
        "multicolor" => "多色模式（四象限独立配色）",
        "main_color" => "主颜色",
        "color_top" => "上",
        "color_bottom" => "下",
        "color_left" => "左",
        "color_right" => "右",
        "hex_hint" => "输入 #RRGGBB",
        "hollow_gap" => "中心缺口（空心）",
        "center_dot" => "中心点大小",
        "outline" => "描边",
        "outline_thickness" => "描边厚度",
        "outline_color" => "描边颜色",
        "outline_opacity" => "描边透明度",
        "dynamic" => "动态准星",
        "fire_expand" => "开火扩散量（px）",
        "recover_ms" => "恢复速度（ms/px）",
        "recoil_indicator" => "后坐力恢复指示条",
        "position" => "位置",
        "center_btn" => "屏幕居中",
        "pos_x" => "X",
        "pos_y" => "Y",
        "monitor" => "显示器",
        "custom_image" => "自定义图片（需选择对应形状）",
        "image_path" => "图片路径",
        "image_scale" => "图片缩放",
        "hotkey" => "快捷键",
        "hotkey_toggle" => "切换准星热键（如 Ctrl+F1）",
        "hotkey_note" => "热键注册系统开发中，当前仅保存配置",
        "right_click" => "右键切换准星",
        "right_click_mode" => "右键模式",
        "gamepad" => "手柄（Apex 瞄准吸附）",
        "ads_mode" => "ADS 模式",
        "ads_button" => "触发键",
        "trigger_threshold" => "触发阈值（0-255）",
        "gamepad_fire_expand" => "右扳机开火驱动扩散",
        "gamepad_note" => "手柄输入系统开发中，当前仅保存配置",
        "presets" => "预设",
        "preset_current" => "当前预设",
        "new_preset" => "创建预设（克隆当前参数）",
        "new_name" => "新预设名",
        "create" => "创建",
        "save" => "保存预设",
        "delete" => "删除预设",
        "cannot_delete_default" => "默认预设不能删除",
        "saved" => "已保存 ✓",
        "created" => "已创建 ✓",
        "deleted" => "已删除 ✓",
        "error" => "错误",
        // 形状名
        "shape_cross" => "十字",
        "shape_dot" => "圆点",
        "shape_square" => "方块",
        "shape_circle" => "圆圈",
        "shape_hollow_cross" => "空心十字",
        "shape_hollow_square" => "空心方框",
        "shape_hollow_cross_dot" => "空心十字加点",
        "shape_chevron" => "箭头 (^)",
        "shape_triangle" => "三角",
        "shape_v_shape" => "V 形",
        "shape_t_shape" => "T 形",
        "shape_brackets" => "四角括号",
        "shape_gap_hair" => "GapHair",
        "shape_custom_image" => "自定义图片",
        // ADS 模式
        "ads_off" => "关闭",
        "ads_hold_hide" => "按住隐藏",
        "ads_toggle" => "扣动切换",
        "ads_hold_show" => "按住显示",
        "ads_left_trigger" => "左扳机 (LT/L2)",
        "ads_right_trigger" => "右扳机 (RT/R2)",
        "rc_click" => "点击切换",
        "rc_hold_show" => "按住显示",
        "rc_hold_hide" => "按住隐藏",
        _ => "",
    }
}

fn en(key: &str) -> &'static str {
    match key {
        "title" => "ACAJA Crosshair Settings",
        "subtitle" => "Closing this window exits the app (tray coming soon)",
        "language" => "Language",
        "theme" => "Theme",
        "theme_auto" => "Auto",
        "theme_light" => "Light",
        "theme_dark" => "Dark",
        "preview" => "Live Preview",
        "show" => "Show Crosshair",
        "hide" => "Hide Crosshair",
        "quit" => "Quit",
        "shape_style" => "Shape & Style",
        "shape" => "Shape",
        "size" => "Size",
        "thickness" => "Thickness",
        "opacity" => "Opacity",
        "rotation" => "Rotation",
        "multicolor" => "Multicolor (independent quadrant colors)",
        "main_color" => "Main Color",
        "color_top" => "Top",
        "color_bottom" => "Bottom",
        "color_left" => "Left",
        "color_right" => "Right",
        "hex_hint" => "Enter #RRGGBB",
        "hollow_gap" => "Gap (hollow)",
        "center_dot" => "Center dot size",
        "outline" => "Outline",
        "outline_thickness" => "Outline thickness",
        "outline_color" => "Outline color",
        "outline_opacity" => "Outline opacity",
        "dynamic" => "Dynamic Crosshair",
        "fire_expand" => "Fire expand (px)",
        "recover_ms" => "Recovery speed (ms/px)",
        "recoil_indicator" => "Recoil recovery indicator",
        "position" => "Position",
        "center_btn" => "Center Screen",
        "pos_x" => "X",
        "pos_y" => "Y",
        "monitor" => "Monitor",
        "custom_image" => "Custom Image (select the shape first)",
        "image_path" => "Image path",
        "image_scale" => "Image scale",
        "hotkey" => "Hotkey",
        "hotkey_toggle" => "Toggle hotkey (e.g. Ctrl+F1)",
        "hotkey_note" => "Hotkey registration system in development — saved only",
        "right_click" => "Right-click toggle",
        "right_click_mode" => "Right-click mode",
        "gamepad" => "Gamepad (Apex aim snapping)",
        "ads_mode" => "ADS mode",
        "ads_button" => "Trigger",
        "trigger_threshold" => "Trigger threshold (0-255)",
        "gamepad_fire_expand" => "Right trigger drives spread",
        "gamepad_note" => "Gamepad input system in development — saved only",
        "presets" => "Presets",
        "preset_current" => "Current preset",
        "new_preset" => "New preset (clone current)",
        "new_name" => "New name",
        "create" => "Create",
        "save" => "Save Preset",
        "delete" => "Delete Preset",
        "cannot_delete_default" => "Default preset cannot be deleted",
        "saved" => "Saved ✓",
        "created" => "Created ✓",
        "deleted" => "Deleted ✓",
        "error" => "Error",
        "shape_cross" => "Cross",
        "shape_dot" => "Dot",
        "shape_square" => "Square",
        "shape_circle" => "Circle",
        "shape_hollow_cross" => "Hollow Cross",
        "shape_hollow_square" => "Hollow Square",
        "shape_hollow_cross_dot" => "Hollow Cross + Dot",
        "shape_chevron" => "Chevron (^)",
        "shape_triangle" => "Triangle",
        "shape_v_shape" => "V Shape",
        "shape_t_shape" => "T Shape",
        "shape_brackets" => "Brackets",
        "shape_gap_hair" => "GapHair",
        "shape_custom_image" => "Custom Image",
        "ads_off" => "Off",
        "ads_hold_hide" => "Hold to hide",
        "ads_toggle" => "Toggle per pull",
        "ads_hold_show" => "Hold to show",
        "ads_left_trigger" => "Left Trigger (LT/L2)",
        "ads_right_trigger" => "Right Trigger (RT/R2)",
        "rc_click" => "Click to toggle",
        "rc_hold_show" => "Hold to show",
        "rc_hold_hide" => "Hold to hide",
        _ => "",
    }
}

/// 形状名文案
pub fn shape_name(lang: Lang, shape: crate::config::Shape) -> &'static str {
    let key = match shape {
        crate::config::Shape::Cross => "shape_cross",
        crate::config::Shape::Dot => "shape_dot",
        crate::config::Shape::Square => "shape_square",
        crate::config::Shape::Circle => "shape_circle",
        crate::config::Shape::HollowCross => "shape_hollow_cross",
        crate::config::Shape::HollowSquare => "shape_hollow_square",
        crate::config::Shape::HollowCrossDot => "shape_hollow_cross_dot",
        crate::config::Shape::Chevron => "shape_chevron",
        crate::config::Shape::Triangle => "shape_triangle",
        crate::config::Shape::VShape => "shape_v_shape",
        crate::config::Shape::TShape => "shape_t_shape",
        crate::config::Shape::Brackets => "shape_brackets",
        crate::config::Shape::GapHair => "shape_gap_hair",
        crate::config::Shape::CustomImage => "shape_custom_image",
    };
    t(lang, key)
}

/// ADS 模式名文案
pub fn ads_mode_name(lang: Lang, mode: AdsMode) -> &'static str {
    let key = match mode {
        AdsMode::Off => "ads_off",
        AdsMode::HoldHide => "ads_hold_hide",
        AdsMode::Toggle => "ads_toggle",
        AdsMode::HoldShow => "ads_hold_show",
    };
    t(lang, key)
}